[build]
  command = "npm install && npm run build"
  functions = "."

[functions]
  directory = "."

[[plugins]]
  package = "@netlify/plugin-functions-schedule"

  [plugins.inputs]
    schedule = "0 */4 * * *"