[build]
  command = "npm install && npm run build"
  functions = "."
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-functions-schedule"

[functions]
  directory = "."
  included_files = ["updatesheet.js"]

[[functions]]
  function = "updatesheet"
  schedule = "0 */4 * * *"