[build]
  command = "npm install -D @netlify/plugin-functions-schedule && npm run build"
  functions = "."
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-functions-schedule"

[functions]
  directory = "."

[[functions]]
  schedule = "0 */4 * * *"
  path = "/updatesheet"